insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('wkidney0@google.pl', 'Willyt', 'Kidney', '5th Floor', 'cP6{EL5s0', 74098);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('bgarner1@studiopress.com', 'Bernelle', 'Garner', 'Room 1190', 'uT2/a8Rrey\', 71400);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('eantonio2@dailymotion.com', 'Evin', 'Antonio', 'Suite 27', 'sU8=Y7''x', 52742);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('apaskins3@google.it', 'Ania', 'Paskins', 'Apt 1492', 'tI2.4Hnj.s=(H', 24492);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('owhyman4@addthis.com', 'Ode', 'Whyman', 'Suite 29', 'yI0?ez6FjzQ', 22348);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('dseaton5@trellian.com', 'Dwight', 'Seaton', '16th Floor', 'oF3<nE(bT,MTXjiL', 43416);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('clyle6@facebook.com', 'Cecil', 'Lyle', '18th Floor', 'xU9.4aaG<6r>', 13032);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('kblewmen7@over-blog.com', 'Kelly', 'Blewmen', '17th Floor', 'gV6+7cQ(Z6\', 77662);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('pmcmillam8@php.net', 'Patin', 'McMillam', 'Apt 1975', 'xD3_C(K3,7#_ne_W', 67681);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('edecourcey9@umich.edu', 'Edouard', 'de Courcey', '5th Floor', 'lX9#`2$dgQv&8#', 21966);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('lfredia@si.edu', 'Leoine', 'Fredi', 'Apt 911', 'xJ0~Id=@${@Ro''s.', 47451);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('rgarnb@go.com', 'Raleigh', 'Garn', 'PO Box 56038', 'rR1_UD52sg.et%', 68117);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('wdenyerc@time.com', 'Worth', 'Denyer', 'Suite 22', 'xZ6`Ssh7h?,F~G', 52229);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('bedlestoned@google.es', 'Brice', 'Edlestone', 'Suite 34', 'eL5"p@TvY8H>', 21882);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('tridgedelle@ihg.com', 'Tresa', 'Ridgedell', 'Apt 1566', 'jM8(o_\7T=r', 30508);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('mvalentinf@ihg.com', 'Michal', 'Valentin', 'Apt 1531', 'lD5$!h2vb', 28143);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('snatwickg@google.co.jp', 'Selena', 'Natwick', 'Suite 51', 'vJ6}Hd9MEH6V', 88639);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('tabrahamsonh@123-reg.co.uk', 'Thorsten', 'Abrahamson', 'Room 1356', 'sF6@cxK$D', 37856);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('jblasketti@bloglovin.com', 'Jammal', 'Blaskett', '1st Floor', 'rM1$sr~=H96Ra~', 57802);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('nnewcomej@surveymonkey.com', 'Nettle', 'Newcome', 'Apt 1488', 'kR2>Mvi9$o<)cDRo', 13804);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('agilhoolk@bluehost.com', 'Anna', 'Gilhool', 'Suite 47', 'xK1~L{9a#<', 44247);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('gwyeldl@auda.org.au', 'Galina', 'Wyeld', 'Apt 453', 'kZ7@3bNI', 18603);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('ibennisonm@ameblo.jp', 'Inglebert', 'Bennison', 'Suite 57', 'wQ3<8M#x}p!7g', 85211);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('frowesn@tmall.com', 'Ferd', 'Rowes', 'PO Box 47654', 'tU0~6$5CY#!aO>**', 34075);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('obodswortho@usatoday.com', 'Odessa', 'Bodsworth', 'Suite 6', 'xY3<oQ4x', 38058);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('ntrittonp@zdnet.com', 'Nester', 'Tritton', '2nd Floor', 'xR5$5Kmyb(', 55474);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('ppomroyq@istockphoto.com', 'Pierson', 'Pomroy', 'Room 1239', 'cB5~6qqCiBPXy', 19943);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('lstockinr@redcross.org', 'Lurette', 'Stockin', 'Room 1756', 'tI8`!o?"JHXmRo', 31184);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('lsummerlys@engadget.com', 'Lotty', 'Summerly', 'Room 1791', 'hM6,n}Zji(+', 39065);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('otatet@storify.com', 'Ofilia', 'Tate', 'Room 935', 'sP8+Mu7kdexX$a?`', 80084);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('apeachu@addtoany.com', 'Ambrosius', 'Peach', 'Suite 31', 'xF0''n5&=DjoR', 63213);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('zdroghanv@quantcast.com', 'Zara', 'Droghan', 'Apt 758', 'vM8,"#/4', 25156);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('fguihenw@xrea.com', 'Faydra', 'Guihen', 'Apt 1297', 'xB9_"B6I~hk', 88632);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('olegrysx@icq.com', 'Ondrea', 'Le Grys', '8th Floor', 'sR5>>\o&BDl13FV', 35787);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('lleregoy@domainmarket.com', 'Lionel', 'Lerego', 'Suite 81', 'yS2&\=A"uH|!L7.D', 22998);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('ewintringhamz@domainmarket.com', 'Eustacia', 'Wintringham', 'Apt 1910', 'sG1=uAt#R}.b', 81593);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('iisacsson10@state.tx.us', 'Ilsa', 'Isacsson', '17th Floor', 'lG9<5&/V<', 79299);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('dhelliwell11@linkedin.com', 'Drew', 'Helliwell', 'Room 902', 'nN0.>,udgPE&A_M', 46984);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('gdobrowolski12@oakley.com', 'Giorgio', 'Dobrowolski', 'Apt 1225', 'oV9<na%#btM#', 64571);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('adabourne13@telegraph.co.uk', 'Annabella', 'Dabourne', 'PO Box 76002', 'uY7|k7I?', 55339);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('gzuker14@mlb.com', 'Granger', 'Zuker', 'Suite 60', 'kC7&~KLVzvs_BF', 64462);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('hcurzon15@imdb.com', 'Hewitt', 'Curzon', 'Room 498', 'tV3*)+Zh', 69605);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('inolli16@seesaa.net', 'Ilyse', 'Nolli', 'Suite 57', 'pZ4$2{$qZb_"', 53682);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('hziem17@tripadvisor.com', 'Henryetta', 'Ziem', 'Apt 863', 'xY3>*%rV', 80571);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('mpetrecz18@about.me', 'Mufi', 'Petrecz', 'PO Box 87592', 'cQ5>o8e<', 42464);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('traisbeck19@irs.gov', 'Toddie', 'Raisbeck', 'Apt 1544', 'aR1_BffJnBp`U', 75624);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('crobecon1a@icio.us', 'Christoforo', 'Robecon', 'Apt 1565', 'dE5)#chwM{|Z@kn', 58806);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('rpock1b@altervista.org', 'Ronni', 'Pock', 'Suite 59', 'hM2"=Js1tA>QQt=', 73224);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('lbartley1c@gmpg.org', 'Luce', 'Bartley', 'PO Box 17621', 'iT1$z\c2', 70039);
insert into Basic_user (E_mail, first_name, last_name, Address, Password, Phone) values ('flittlejohn1d@amazon.de', 'Frederique', 'Littlejohn', 'Suite 66', 'tJ4\jTx45>f\8', 21952);
