ALTER TABLE SHOP_OWNS
DROP CONSTRAINT product_s_fk;

ALTER TABLE SHOP_OWNS
ADD CONSTRAINT product_s_fk
FOREIGN KEY (PRODUCT_ID)
REFERENCES PRODUCT (PRODUCT_ID)
ON DELETE CASCADE;

ALTER TABLE seller_owns
DROP CONSTRAINT  product_selsp_fk;

ALTER TABLE seller_owns
ADD CONSTRAINT product_selsp_fk
FOREIGN KEY (PRODUCT_ID)
REFERENCES PRODUCT (PRODUCT_ID)
ON DELETE CASCADE;

ALTER TABLE Cart_has
DROP CONSTRAINT  product_c_fk;

ALTER TABLE Cart_has
ADD CONSTRAINT product_c_fk
FOREIGN KEY (PRODUCT_ID)
REFERENCES PRODUCT (PRODUCT_ID)
ON DELETE CASCADE;



ALTER TABLE product_orders
DROP CONSTRAINT  product_pop_fk;

ALTER TABLE product_orders
ADD CONSTRAINT product_pop_fk
FOREIGN KEY (PRODUCT_ID)
REFERENCES PRODUCT (PRODUCT_ID)
ON DELETE CASCADE;
-----------------------------------------------New---------------------
ALTER TABLE product_orders
DROP CONSTRAINT  order_pop_fk ;

ALTER TABLE product_orders
ADD CONSTRAINT order_pop_fk 
FOREIGN KEY (ORDER_ID)
REFERENCES ORDERS (ORDER_ID)
ON DELETE CASCADE;

ALTER TABLE PAYMENT
DROP CONSTRAINT  order_op_fk ;

ALTER TABLE PAYMENT
ADD CONSTRAINT order_op_fk 
FOREIGN KEY (ORDER_ID)
REFERENCES ORDERS (ORDER_ID)
ON DELETE CASCADE;

ALTER TABLE FINAL_ORDERS
DROP CONSTRAINT   order_fo_fk;

ALTER TABLE FINAL_ORDERS
ADD CONSTRAINT  order_fo_fk
FOREIGN KEY (ORDER_ID)
REFERENCES ORDERS (ORDER_ID)
ON DELETE CASCADE;

ALTER TABLE SHIPPING
DROP CONSTRAINT order_sp_fk;

ALTER TABLE SHIPPING
ADD CONSTRAINT  order_sp_fk
FOREIGN KEY (ORDER_ID)
REFERENCES ORDERS (ORDER_ID)
ON DELETE CASCADE;







