CREATE OR REPLACE PROCEDURE ADD_A_PRODUCT(NAM IN VARCHAR2, GENDER_CATGORY IN VARCHAR2, TYPOF IN VARCHAR2, MATRIAL IN VARCHAR2, PRICEE IN NUMBER, QUANTTY IN NUMBER, IMG IN VARCHAR2, SIZEOF IN NUMBER, SELLER_T IN VARCHAR2, USESTATUS IN VARCHAR2, SHOPID IN NUMBER) IS

new_product_id NUMBER;

BEGIN 
INSERT INTO PRODUCT(NAME,GENDER_CATEGORY,TYPE_OF,MATERIAL,PRICE,QUANTITY,IMAGE,SIZE_OF,SELLER_TYPE,USED_STATUS) VALUES(NAM,GENDER_CATGORY,TYPOF,MATRIAL,PRICEE,QUANTTY,IMG,SIZEOF,SELLER_T,USESTATUS) RETURNING PRODUCT_ID INTO new_product_id;

INSERT INTO SHOP_OWNS(PRODUCT_ID,SHOP_ID) VALUES(new_product_id,SHOPID);
END;
/

CREATE OR REPLACE PROCEDURE ADD_A_PRODUCT_FROM_SELLER(NAM IN VARCHAR2, GENDER_CATGORY IN VARCHAR2, TYPOF IN VARCHAR2, MATRIAL IN VARCHAR2, PRICEE IN NUMBER, QUANTTY IN NUMBER, IMG IN VARCHAR2, SIZEOF IN NUMBER, SELLER_T IN VARCHAR2, USESTATUS IN VARCHAR2, SELLERID IN NUMBER) IS

new_product_id NUMBER;

BEGIN 
INSERT INTO PRODUCT(NAME,GENDER_CATEGORY,TYPE_OF,MATERIAL,PRICE,QUANTITY,IMAGE,SIZE_OF,SELLER_TYPE,USED_STATUS) VALUES(NAM,GENDER_CATGORY,TYPOF,MATRIAL,PRICEE,QUANTTY,IMG,SIZEOF,SELLER_T,USESTATUS) RETURNING PRODUCT_ID INTO new_product_id;

INSERT INTO SELLER_OWNS(PRODUCT_ID,SELLER_ID) VALUES(new_product_id,SELLERID);
END;
/

CREATE OR REPLACE FUNCTION CREATE_NEW_ORDER( CID IN NUMBER)
RETURN NUMBER IS 
OID NUMBER;
BEGIN
INSERT INTO ORDERS(CART_ID, ORDER_STATUS, ORDER_DATE) VALUES(CID, 'processing', SYSDATE) RETURNING ORDER_ID INTO OID;
RETURN OID;
END;
/


	
	CREATE OR REPLACE FUNCTION TOTAL_SALE (ID IN NUMBER) RETURN NUMBER
	IS
	SALE NUMBER;
	BEGIN
	select COUNT(*) INTO SALE from PRODUCT_ORDERS PO JOIN SHOP_OWNS SO ON (PO.PRODUCT_ID=SO.PRODUCT_ID) WHERE SO.SHOP_ID=ID;
	RETURN SALE;
	END;
	/


    CREATE OR REPLACE FUNCTION TOTAL_SALE_OF_SELLER (ID IN NUMBER) RETURN NUMBER
	IS
	SALE NUMBER;
	BEGIN
	select COUNT(*) INTO SALE from PRODUCT_ORDERS PO JOIN SELLER_OWNS SO ON (PO.PRODUCT_ID=SO.PRODUCT_ID) WHERE SO.SELLER_ID=ID;
	RETURN SALE;
	END;
	/